server:
  port: 5000

spring:
  servlet:
    # 文件上传限制
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    # mongodb
    mongodb:
      uri: mongodb://127.0.0.1:27017/reportPicture
  #RabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    virtualHost: /
  application:
    name: report-game
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848