server:
  port: 9091

spring:
  servlet:
    # 文件上传限制
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    # mongodb
    mongodb:
      uri: mongodb://127.0.0.1:27017/reportPicture
  #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 7000
  #RabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    virtualHost: /