server:
  port: 9091

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/reportPicture


file:
  update:
    url: /Users/martin/Desktop