server:
  port: 9092

spring:
  #RabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    virtualHost: /
  #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 7000