server:
  port: 1100

spring:
  #RabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    virtualHost: /
  #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 7000
  application:
    name: audit-report-game
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848