server:
  port: 9090
# 数据源-开发
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/windcraft?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: MysqlSunyinuo15332#
    driver-class-name: com.mysql.cj.jdbc.Driver
# log4j2
logging:
  level:
    cn.jay.repository: trace