server:
  port: 9090
# 数据源
spring:
  datasource:
    dynamic:
      primary: mysql-development
      strict: false #不严格匹配数据源
      datasource:
        #开发数据源-暂时不契合生产环境数据库的多库
        mysql-development:
          url: jdbc:mysql://localhost:3306/windcraft
          username: root
          password: MysqlSunyinuo15332#
          driver-class-name: com.mysql.cj.jdbc.Driver

  # redis caching
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    timeout: 3000ms
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3000ms
        min-idle: 20
# log4j2
logging:
  level:
    cn.jay.repository: trace